### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(QTDesignTestContent)
add_subdirectory(Generated)
add_subdirectory(QTDesignTest)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    QTDesignTestContentplugin
    Generated_Bundles_Effectsplugin
    Generated_Bundles_Materialsplugin
    QTDesignTestplugin)